// This file contains an inventory PB for a device

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.6.1
// source: proto_signals/proto_signals.proto

package proto_signals

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Sig int32

const (
	Sig_PLAN      Sig = 0
	Sig_DEPLOY    Sig = 1
	Sig_GENCONFIG Sig = 2
)

// Enum value maps for Sig.
var (
	Sig_name = map[int32]string{
		0: "PLAN",
		1: "DEPLOY",
		2: "GENCONFIG",
	}
	Sig_value = map[string]int32{
		"PLAN":      0,
		"DEPLOY":    1,
		"GENCONFIG": 2,
	}
)

func (x Sig) Enum() *Sig {
	p := new(Sig)
	*p = x
	return p
}

func (x Sig) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Sig) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_signals_proto_signals_proto_enumTypes[0].Descriptor()
}

func (Sig) Type() protoreflect.EnumType {
	return &file_proto_signals_proto_signals_proto_enumTypes[0]
}

func (x Sig) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Sig.Descriptor instead.
func (Sig) EnumDescriptor() ([]byte, []int) {
	return file_proto_signals_proto_signals_proto_rawDescGZIP(), []int{0}
}

type Signal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sig  Sig    `protobuf:"varint,1,opt,name=Sig,proto3,enum=Sig" json:"Sig,omitempty"`
	UUID string `protobuf:"bytes,2,opt,name=UUID,proto3" json:"UUID,omitempty"`
}

func (x *Signal) Reset() {
	*x = Signal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_signals_proto_signals_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Signal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signal) ProtoMessage() {}

func (x *Signal) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signals_proto_signals_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signal.ProtoReflect.Descriptor instead.
func (*Signal) Descriptor() ([]byte, []int) {
	return file_proto_signals_proto_signals_proto_rawDescGZIP(), []int{0}
}

func (x *Signal) GetSig() Sig {
	if x != nil {
		return x.Sig
	}
	return Sig_PLAN
}

func (x *Signal) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

var File_proto_signals_proto_signals_proto protoreflect.FileDescriptor

var file_proto_signals_proto_signals_proto_rawDesc = []byte{
	0x0a, 0x21, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x73, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x34, 0x0a, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x12, 0x16, 0x0a,
	0x03, 0x53, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x04, 0x2e, 0x53, 0x69, 0x67,
	0x52, 0x03, 0x53, 0x69, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x55, 0x55, 0x49, 0x44, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x55, 0x55, 0x49, 0x44, 0x2a, 0x2a, 0x0a, 0x03, 0x53, 0x69, 0x67,
	0x12, 0x08, 0x0a, 0x04, 0x50, 0x4c, 0x41, 0x4e, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x45,
	0x50, 0x4c, 0x4f, 0x59, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x47, 0x45, 0x4e, 0x43, 0x4f, 0x4e,
	0x46, 0x49, 0x47, 0x10, 0x02, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x61, 0x76, 0x65, 0x64, 0x6f, 0x74, 0x64, 0x65, 0x76, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x64, 0x64, 0x69, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x5f, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_signals_proto_signals_proto_rawDescOnce sync.Once
	file_proto_signals_proto_signals_proto_rawDescData = file_proto_signals_proto_signals_proto_rawDesc
)

func file_proto_signals_proto_signals_proto_rawDescGZIP() []byte {
	file_proto_signals_proto_signals_proto_rawDescOnce.Do(func() {
		file_proto_signals_proto_signals_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_signals_proto_signals_proto_rawDescData)
	})
	return file_proto_signals_proto_signals_proto_rawDescData
}

var file_proto_signals_proto_signals_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_signals_proto_signals_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_signals_proto_signals_proto_goTypes = []interface{}{
	(Sig)(0),       // 0: Sig
	(*Signal)(nil), // 1: Signal
}
var file_proto_signals_proto_signals_proto_depIdxs = []int32{
	0, // 0: Signal.Sig:type_name -> Sig
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_signals_proto_signals_proto_init() }
func file_proto_signals_proto_signals_proto_init() {
	if File_proto_signals_proto_signals_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_signals_proto_signals_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Signal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_signals_proto_signals_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_signals_proto_signals_proto_goTypes,
		DependencyIndexes: file_proto_signals_proto_signals_proto_depIdxs,
		EnumInfos:         file_proto_signals_proto_signals_proto_enumTypes,
		MessageInfos:      file_proto_signals_proto_signals_proto_msgTypes,
	}.Build()
	File_proto_signals_proto_signals_proto = out.File
	file_proto_signals_proto_signals_proto_rawDesc = nil
	file_proto_signals_proto_signals_proto_goTypes = nil
	file_proto_signals_proto_signals_proto_depIdxs = nil
}
