// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto_vertex/proto_vertex.proto

package proto_vertex

import (
	fmt "fmt"
	proto_common "github.com/davedotdev/proto/eddie/proto_common"
	proto_node "github.com/davedotdev/proto/eddie/proto_node"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type VERTEXLIST struct {
	Vertex               []*VERTEX `protobuf:"bytes,1,rep,name=vertex,proto3" json:"vertex,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *VERTEXLIST) Reset()         { *m = VERTEXLIST{} }
func (m *VERTEXLIST) String() string { return proto.CompactTextString(m) }
func (*VERTEXLIST) ProtoMessage()    {}
func (*VERTEXLIST) Descriptor() ([]byte, []int) {
	return fileDescriptor_e2212334cf777586, []int{0}
}

func (m *VERTEXLIST) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VERTEXLIST.Unmarshal(m, b)
}
func (m *VERTEXLIST) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VERTEXLIST.Marshal(b, m, deterministic)
}
func (m *VERTEXLIST) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VERTEXLIST.Merge(m, src)
}
func (m *VERTEXLIST) XXX_Size() int {
	return xxx_messageInfo_VERTEXLIST.Size(m)
}
func (m *VERTEXLIST) XXX_DiscardUnknown() {
	xxx_messageInfo_VERTEXLIST.DiscardUnknown(m)
}

var xxx_messageInfo_VERTEXLIST proto.InternalMessageInfo

func (m *VERTEXLIST) GetVertex() []*VERTEX {
	if m != nil {
		return m.Vertex
	}
	return nil
}

type VERTEX struct {
	RelIdentity          int64                  `protobuf:"varint,1,opt,name=RelIdentity,proto3" json:"RelIdentity,omitempty"`
	NodeA                *proto_node.NODE       `protobuf:"bytes,2,opt,name=nodeA,proto3" json:"nodeA,omitempty"`
	NodeB                *proto_node.NODE       `protobuf:"bytes,3,opt,name=nodeB,proto3" json:"nodeB,omitempty"`
	Type                 string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Operation            proto_common.Operation `protobuf:"varint,5,opt,name=operation,proto3,enum=Operation" json:"operation,omitempty"`
	Kv                   []*proto_common.KV     `protobuf:"bytes,6,rep,name=kv,proto3" json:"kv,omitempty"`
	Updatedkv            []*proto_common.KV     `protobuf:"bytes,7,rep,name=updatedkv,proto3" json:"updatedkv,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *VERTEX) Reset()         { *m = VERTEX{} }
func (m *VERTEX) String() string { return proto.CompactTextString(m) }
func (*VERTEX) ProtoMessage()    {}
func (*VERTEX) Descriptor() ([]byte, []int) {
	return fileDescriptor_e2212334cf777586, []int{1}
}

func (m *VERTEX) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VERTEX.Unmarshal(m, b)
}
func (m *VERTEX) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VERTEX.Marshal(b, m, deterministic)
}
func (m *VERTEX) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VERTEX.Merge(m, src)
}
func (m *VERTEX) XXX_Size() int {
	return xxx_messageInfo_VERTEX.Size(m)
}
func (m *VERTEX) XXX_DiscardUnknown() {
	xxx_messageInfo_VERTEX.DiscardUnknown(m)
}

var xxx_messageInfo_VERTEX proto.InternalMessageInfo

func (m *VERTEX) GetRelIdentity() int64 {
	if m != nil {
		return m.RelIdentity
	}
	return 0
}

func (m *VERTEX) GetNodeA() *proto_node.NODE {
	if m != nil {
		return m.NodeA
	}
	return nil
}

func (m *VERTEX) GetNodeB() *proto_node.NODE {
	if m != nil {
		return m.NodeB
	}
	return nil
}

func (m *VERTEX) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *VERTEX) GetOperation() proto_common.Operation {
	if m != nil {
		return m.Operation
	}
	return proto_common.Operation_CREATE
}

func (m *VERTEX) GetKv() []*proto_common.KV {
	if m != nil {
		return m.Kv
	}
	return nil
}

func (m *VERTEX) GetUpdatedkv() []*proto_common.KV {
	if m != nil {
		return m.Updatedkv
	}
	return nil
}

type VERTEXLITE struct {
	RelIdentity          int64                  `protobuf:"varint,1,opt,name=RelIdentity,proto3" json:"RelIdentity,omitempty"`
	EndA                 int64                  `protobuf:"varint,2,opt,name=EndA,proto3" json:"EndA,omitempty"`
	EndB                 int64                  `protobuf:"varint,3,opt,name=EndB,proto3" json:"EndB,omitempty"`
	Type                 string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Operation            proto_common.Operation `protobuf:"varint,5,opt,name=operation,proto3,enum=Operation" json:"operation,omitempty"`
	Kv                   []*proto_common.KV     `protobuf:"bytes,6,rep,name=kv,proto3" json:"kv,omitempty"`
	Updatedkv            []*proto_common.KV     `protobuf:"bytes,7,rep,name=updatedkv,proto3" json:"updatedkv,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *VERTEXLITE) Reset()         { *m = VERTEXLITE{} }
func (m *VERTEXLITE) String() string { return proto.CompactTextString(m) }
func (*VERTEXLITE) ProtoMessage()    {}
func (*VERTEXLITE) Descriptor() ([]byte, []int) {
	return fileDescriptor_e2212334cf777586, []int{2}
}

func (m *VERTEXLITE) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VERTEXLITE.Unmarshal(m, b)
}
func (m *VERTEXLITE) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VERTEXLITE.Marshal(b, m, deterministic)
}
func (m *VERTEXLITE) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VERTEXLITE.Merge(m, src)
}
func (m *VERTEXLITE) XXX_Size() int {
	return xxx_messageInfo_VERTEXLITE.Size(m)
}
func (m *VERTEXLITE) XXX_DiscardUnknown() {
	xxx_messageInfo_VERTEXLITE.DiscardUnknown(m)
}

var xxx_messageInfo_VERTEXLITE proto.InternalMessageInfo

func (m *VERTEXLITE) GetRelIdentity() int64 {
	if m != nil {
		return m.RelIdentity
	}
	return 0
}

func (m *VERTEXLITE) GetEndA() int64 {
	if m != nil {
		return m.EndA
	}
	return 0
}

func (m *VERTEXLITE) GetEndB() int64 {
	if m != nil {
		return m.EndB
	}
	return 0
}

func (m *VERTEXLITE) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *VERTEXLITE) GetOperation() proto_common.Operation {
	if m != nil {
		return m.Operation
	}
	return proto_common.Operation_CREATE
}

func (m *VERTEXLITE) GetKv() []*proto_common.KV {
	if m != nil {
		return m.Kv
	}
	return nil
}

func (m *VERTEXLITE) GetUpdatedkv() []*proto_common.KV {
	if m != nil {
		return m.Updatedkv
	}
	return nil
}

type VERTEXLITELIST struct {
	Vertexlite           []*VERTEXLITE `protobuf:"bytes,1,rep,name=vertexlite,proto3" json:"vertexlite,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *VERTEXLITELIST) Reset()         { *m = VERTEXLITELIST{} }
func (m *VERTEXLITELIST) String() string { return proto.CompactTextString(m) }
func (*VERTEXLITELIST) ProtoMessage()    {}
func (*VERTEXLITELIST) Descriptor() ([]byte, []int) {
	return fileDescriptor_e2212334cf777586, []int{3}
}

func (m *VERTEXLITELIST) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VERTEXLITELIST.Unmarshal(m, b)
}
func (m *VERTEXLITELIST) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VERTEXLITELIST.Marshal(b, m, deterministic)
}
func (m *VERTEXLITELIST) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VERTEXLITELIST.Merge(m, src)
}
func (m *VERTEXLITELIST) XXX_Size() int {
	return xxx_messageInfo_VERTEXLITELIST.Size(m)
}
func (m *VERTEXLITELIST) XXX_DiscardUnknown() {
	xxx_messageInfo_VERTEXLITELIST.DiscardUnknown(m)
}

var xxx_messageInfo_VERTEXLITELIST proto.InternalMessageInfo

func (m *VERTEXLITELIST) GetVertexlite() []*VERTEXLITE {
	if m != nil {
		return m.Vertexlite
	}
	return nil
}

func init() {
	proto.RegisterType((*VERTEXLIST)(nil), "VERTEXLIST")
	proto.RegisterType((*VERTEX)(nil), "VERTEX")
	proto.RegisterType((*VERTEXLITE)(nil), "VERTEXLITE")
	proto.RegisterType((*VERTEXLITELIST)(nil), "VERTEXLITELIST")
}

func init() { proto.RegisterFile("proto_vertex/proto_vertex.proto", fileDescriptor_e2212334cf777586) }

var fileDescriptor_e2212334cf777586 = []byte{
	// 328 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x92, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0xc9, 0xba, 0x75, 0xec, 0x15, 0x76, 0x88, 0x97, 0xe0, 0x0e, 0xab, 0x3b, 0x15, 0xc4,
	0x54, 0xe6, 0xd9, 0x83, 0xc3, 0x1e, 0x86, 0xe2, 0x20, 0x8e, 0x21, 0x5e, 0x64, 0x5b, 0x1e, 0x5a,
	0xb6, 0x35, 0xa5, 0x64, 0xc1, 0x7d, 0x47, 0x3f, 0x81, 0x9f, 0x46, 0x4c, 0x3a, 0x52, 0xf1, 0xe2,
	0xcd, 0xdb, 0xfb, 0xff, 0xfe, 0x2f, 0x21, 0xff, 0xbc, 0x07, 0xc3, 0xb2, 0x52, 0x5a, 0xbd, 0x18,
	0xac, 0x34, 0xbe, 0xa7, 0x4d, 0xc1, 0xad, 0x38, 0x1d, 0x38, 0x56, 0x28, 0x89, 0xa9, 0x2f, 0x6b,
	0xb3, 0x3e, 0xbd, 0x56, 0xbb, 0x9d, 0x2a, 0xd2, 0xa6, 0x70, 0x0d, 0xa3, 0x0b, 0x80, 0x45, 0x26,
	0xe6, 0xd9, 0xd3, 0xfd, 0xf4, 0x71, 0x4e, 0x87, 0x10, 0xba, 0xbb, 0x19, 0x89, 0x83, 0x24, 0x1a,
	0x77, 0xb9, 0x33, 0x45, 0x8d, 0x47, 0x9f, 0x04, 0x42, 0x87, 0x68, 0x0c, 0x91, 0xc0, 0xed, 0x54,
	0x62, 0xa1, 0x73, 0x7d, 0x60, 0x24, 0x26, 0x49, 0x20, 0x9a, 0x88, 0x0e, 0xa0, 0xf3, 0xfd, 0x94,
	0x1b, 0xd6, 0x8a, 0x49, 0x12, 0x8d, 0x3b, 0xfc, 0x61, 0x76, 0x9b, 0x09, 0xc7, 0x8e, 0xe6, 0x84,
	0x05, 0xbf, 0xcc, 0x09, 0xa5, 0xd0, 0xd6, 0x87, 0x12, 0x59, 0x3b, 0x26, 0x49, 0x4f, 0xd8, 0x9a,
	0x26, 0xd0, 0x53, 0x25, 0x56, 0x4b, 0x9d, 0xab, 0x82, 0x75, 0x62, 0x92, 0xf4, 0xc7, 0xc0, 0x67,
	0x47, 0x22, 0xbc, 0x49, 0x4f, 0xa0, 0xb5, 0x31, 0x2c, 0xb4, 0x09, 0x02, 0x7e, 0xb7, 0x10, 0xad,
	0x8d, 0xa1, 0x67, 0xd0, 0xdb, 0x97, 0x72, 0xa9, 0x51, 0x6e, 0x0c, 0xeb, 0x7a, 0xcf, 0xd3, 0xd1,
	0x07, 0xf1, 0x9f, 0x31, 0xcf, 0xfe, 0x10, 0x90, 0x42, 0x3b, 0x2b, 0xa4, 0xcb, 0x17, 0x08, 0x5b,
	0xd7, 0xcc, 0xc5, 0x72, 0xec, 0xbf, 0xe2, 0x5c, 0x43, 0xdf, 0xa7, 0xb1, 0xe3, 0x3d, 0x07, 0x70,
	0x73, 0xdc, 0xe6, 0x1a, 0xeb, 0x11, 0x47, 0xdc, 0x37, 0x89, 0x86, 0x3d, 0xb9, 0x7c, 0xe6, 0xaf,
	0xb9, 0x7e, 0xdb, 0xaf, 0xf8, 0x5a, 0xed, 0x52, 0xb9, 0x34, 0x28, 0x95, 0x96, 0x68, 0xdc, 0x16,
	0xa5, 0x28, 0x65, 0x8e, 0x3f, 0xf6, 0x71, 0x15, 0x5a, 0x75, 0xf5, 0x15, 0x00, 0x00, 0xff, 0xff,
	0x0e, 0x72, 0x00, 0xb2, 0xb3, 0x02, 0x00, 0x00,
}
