// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto_vertex/proto_vertex.proto

package proto_vertex

import (
	fmt "fmt"
	proto_common "github.com/davedotdev/proto/eddie/proto_common"
	proto_node "github.com/davedotdev/proto/eddie/proto_node"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type VERTEXLIST struct {
	Vertex               []*VERTEX `protobuf:"bytes,1,rep,name=vertex,proto3" json:"vertex,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *VERTEXLIST) Reset()         { *m = VERTEXLIST{} }
func (m *VERTEXLIST) String() string { return proto.CompactTextString(m) }
func (*VERTEXLIST) ProtoMessage()    {}
func (*VERTEXLIST) Descriptor() ([]byte, []int) {
	return fileDescriptor_e2212334cf777586, []int{0}
}

func (m *VERTEXLIST) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VERTEXLIST.Unmarshal(m, b)
}
func (m *VERTEXLIST) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VERTEXLIST.Marshal(b, m, deterministic)
}
func (m *VERTEXLIST) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VERTEXLIST.Merge(m, src)
}
func (m *VERTEXLIST) XXX_Size() int {
	return xxx_messageInfo_VERTEXLIST.Size(m)
}
func (m *VERTEXLIST) XXX_DiscardUnknown() {
	xxx_messageInfo_VERTEXLIST.DiscardUnknown(m)
}

var xxx_messageInfo_VERTEXLIST proto.InternalMessageInfo

func (m *VERTEXLIST) GetVertex() []*VERTEX {
	if m != nil {
		return m.Vertex
	}
	return nil
}

type VERTEX struct {
	RelIdentity          int64                  `protobuf:"varint,1,opt,name=RelIdentity,proto3" json:"RelIdentity,omitempty"`
	NodeA                *proto_node.NODE       `protobuf:"bytes,2,opt,name=nodeA,proto3" json:"nodeA,omitempty"`
	NodeB                *proto_node.NODE       `protobuf:"bytes,3,opt,name=nodeB,proto3" json:"nodeB,omitempty"`
	Type                 string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Operation            proto_common.Operation `protobuf:"varint,5,opt,name=operation,proto3,enum=Operation" json:"operation,omitempty"`
	Kv                   []*proto_common.KV     `protobuf:"bytes,6,rep,name=kv,proto3" json:"kv,omitempty"`
	Updatedkv            []*proto_common.KV     `protobuf:"bytes,7,rep,name=updatedkv,proto3" json:"updatedkv,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *VERTEX) Reset()         { *m = VERTEX{} }
func (m *VERTEX) String() string { return proto.CompactTextString(m) }
func (*VERTEX) ProtoMessage()    {}
func (*VERTEX) Descriptor() ([]byte, []int) {
	return fileDescriptor_e2212334cf777586, []int{1}
}

func (m *VERTEX) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VERTEX.Unmarshal(m, b)
}
func (m *VERTEX) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VERTEX.Marshal(b, m, deterministic)
}
func (m *VERTEX) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VERTEX.Merge(m, src)
}
func (m *VERTEX) XXX_Size() int {
	return xxx_messageInfo_VERTEX.Size(m)
}
func (m *VERTEX) XXX_DiscardUnknown() {
	xxx_messageInfo_VERTEX.DiscardUnknown(m)
}

var xxx_messageInfo_VERTEX proto.InternalMessageInfo

func (m *VERTEX) GetRelIdentity() int64 {
	if m != nil {
		return m.RelIdentity
	}
	return 0
}

func (m *VERTEX) GetNodeA() *proto_node.NODE {
	if m != nil {
		return m.NodeA
	}
	return nil
}

func (m *VERTEX) GetNodeB() *proto_node.NODE {
	if m != nil {
		return m.NodeB
	}
	return nil
}

func (m *VERTEX) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *VERTEX) GetOperation() proto_common.Operation {
	if m != nil {
		return m.Operation
	}
	return proto_common.Operation_CREATE
}

func (m *VERTEX) GetKv() []*proto_common.KV {
	if m != nil {
		return m.Kv
	}
	return nil
}

func (m *VERTEX) GetUpdatedkv() []*proto_common.KV {
	if m != nil {
		return m.Updatedkv
	}
	return nil
}

func init() {
	proto.RegisterType((*VERTEXLIST)(nil), "VERTEXLIST")
	proto.RegisterType((*VERTEX)(nil), "VERTEX")
}

func init() { proto.RegisterFile("proto_vertex/proto_vertex.proto", fileDescriptor_e2212334cf777586) }

var fileDescriptor_e2212334cf777586 = []byte{
	// 277 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0x41, 0x4b, 0xf3, 0x30,
	0x18, 0xc7, 0xc9, 0xba, 0x75, 0xec, 0x19, 0xbc, 0x87, 0xbc, 0x97, 0xe0, 0x0e, 0x8b, 0x3b, 0xe5,
	0x62, 0x2a, 0xf5, 0x13, 0x58, 0xec, 0x61, 0x28, 0x0e, 0xe2, 0x18, 0xe2, 0x45, 0xba, 0xe5, 0x41,
	0x4b, 0x6d, 0x53, 0x4a, 0x16, 0xdc, 0x57, 0xf5, 0xd3, 0x88, 0x4d, 0x47, 0x2b, 0xde, 0xfe, 0xff,
	0xdf, 0x2f, 0x09, 0x49, 0x1e, 0x58, 0xd6, 0x8d, 0xb1, 0xe6, 0xd5, 0x61, 0x63, 0xf1, 0x33, 0x1a,
	0x16, 0xd9, 0x96, 0x8b, 0x85, 0x67, 0x95, 0xd1, 0x18, 0xf5, 0xb1, 0x93, 0xdd, 0xee, 0x83, 0x29,
	0x4b, 0x53, 0x45, 0xc3, 0xe2, 0x17, 0xac, 0xae, 0x00, 0x76, 0xa9, 0xda, 0xa6, 0xcf, 0x0f, 0xeb,
	0xa7, 0x2d, 0x5d, 0x42, 0xe8, 0xcf, 0x66, 0x84, 0x07, 0x62, 0x1e, 0x4f, 0xa5, 0x97, 0xaa, 0xc3,
	0xab, 0x2f, 0x02, 0xa1, 0x47, 0x94, 0xc3, 0x5c, 0xe1, 0xc7, 0x5a, 0x63, 0x65, 0x73, 0x7b, 0x62,
	0x84, 0x13, 0x11, 0xa8, 0x21, 0xa2, 0x0b, 0x98, 0xfc, 0x5c, 0xe5, 0x96, 0x8d, 0x38, 0x11, 0xf3,
	0x78, 0x22, 0x1f, 0x37, 0x77, 0xa9, 0xf2, 0xec, 0x2c, 0x13, 0x16, 0xfc, 0x91, 0x09, 0xa5, 0x30,
	0xb6, 0xa7, 0x1a, 0xd9, 0x98, 0x13, 0x31, 0x53, 0x6d, 0xa6, 0x02, 0x66, 0xa6, 0xc6, 0x26, 0xb3,
	0xb9, 0xa9, 0xd8, 0x84, 0x13, 0xf1, 0x2f, 0x06, 0xb9, 0x39, 0x13, 0xd5, 0x4b, 0xfa, 0x1f, 0x46,
	0x85, 0x63, 0x61, 0xfb, 0x82, 0x40, 0xde, 0xef, 0xd4, 0xa8, 0x70, 0xf4, 0x12, 0x66, 0xc7, 0x5a,
	0x67, 0x16, 0x75, 0xe1, 0xd8, 0xb4, 0x77, 0x3d, 0x4d, 0xae, 0x5f, 0xe4, 0x5b, 0x6e, 0xdf, 0x8f,
	0x7b, 0x79, 0x30, 0x65, 0xa4, 0x33, 0x87, 0xda, 0x58, 0x8d, 0xce, 0xff, 0x5b, 0x84, 0x5a, 0xe7,
	0xf8, 0x6b, 0x02, 0xfb, 0xb0, 0x6d, 0x37, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x18, 0x04, 0xf0,
	0xae, 0xa5, 0x01, 0x00, 0x00,
}
