// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto_common/proto_common.proto

package proto_common

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Operation int32

const (
	Operation_CREATE Operation = 0
	Operation_READ   Operation = 1
	Operation_UPDATE Operation = 2
	Operation_DELETE Operation = 3
)

var Operation_name = map[int32]string{
	0: "CREATE",
	1: "READ",
	2: "UPDATE",
	3: "DELETE",
}

var Operation_value = map[string]int32{
	"CREATE": 0,
	"READ":   1,
	"UPDATE": 2,
	"DELETE": 3,
}

func (x Operation) String() string {
	return proto.EnumName(Operation_name, int32(x))
}

func (Operation) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3f3ad5992816bccd, []int{0}
}

type T int32

const (
	// Inline with Neo types. Float is a point.
	T_STRING        T = 0
	T_INT64         T = 1
	T_FLOAT64       T = 2
	T_BOOL          T = 3
	T_SLICE_STRING  T = 4
	T_SLICE_INT64   T = 5
	T_SLICE_FLOAT64 T = 6
	T_SLICE_BOOL    T = 7
)

var T_name = map[int32]string{
	0: "STRING",
	1: "INT64",
	2: "FLOAT64",
	3: "BOOL",
	4: "SLICE_STRING",
	5: "SLICE_INT64",
	6: "SLICE_FLOAT64",
	7: "SLICE_BOOL",
}

var T_value = map[string]int32{
	"STRING":        0,
	"INT64":         1,
	"FLOAT64":       2,
	"BOOL":          3,
	"SLICE_STRING":  4,
	"SLICE_INT64":   5,
	"SLICE_FLOAT64": 6,
	"SLICE_BOOL":    7,
}

func (x T) String() string {
	return proto.EnumName(T_name, int32(x))
}

func (T) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3f3ad5992816bccd, []int{1}
}

type KV struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Vtype                T        `protobuf:"varint,3,opt,name=vtype,proto3,enum=T" json:"vtype,omitempty"`
	Disabled             bool     `protobuf:"varint,4,opt,name=disabled,proto3" json:"disabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KV) Reset()         { *m = KV{} }
func (m *KV) String() string { return proto.CompactTextString(m) }
func (*KV) ProtoMessage()    {}
func (*KV) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f3ad5992816bccd, []int{0}
}

func (m *KV) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KV.Unmarshal(m, b)
}
func (m *KV) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KV.Marshal(b, m, deterministic)
}
func (m *KV) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KV.Merge(m, src)
}
func (m *KV) XXX_Size() int {
	return xxx_messageInfo_KV.Size(m)
}
func (m *KV) XXX_DiscardUnknown() {
	xxx_messageInfo_KV.DiscardUnknown(m)
}

var xxx_messageInfo_KV proto.InternalMessageInfo

func (m *KV) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KV) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *KV) GetVtype() T {
	if m != nil {
		return m.Vtype
	}
	return T_STRING
}

func (m *KV) GetDisabled() bool {
	if m != nil {
		return m.Disabled
	}
	return false
}

type Do struct {
	Operator             Operation `protobuf:"varint,1,opt,name=Operator,proto3,enum=Operation" json:"Operator,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Do) Reset()         { *m = Do{} }
func (m *Do) String() string { return proto.CompactTextString(m) }
func (*Do) ProtoMessage()    {}
func (*Do) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f3ad5992816bccd, []int{1}
}

func (m *Do) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Do.Unmarshal(m, b)
}
func (m *Do) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Do.Marshal(b, m, deterministic)
}
func (m *Do) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Do.Merge(m, src)
}
func (m *Do) XXX_Size() int {
	return xxx_messageInfo_Do.Size(m)
}
func (m *Do) XXX_DiscardUnknown() {
	xxx_messageInfo_Do.DiscardUnknown(m)
}

var xxx_messageInfo_Do proto.InternalMessageInfo

func (m *Do) GetOperator() Operation {
	if m != nil {
		return m.Operator
	}
	return Operation_CREATE
}

func init() {
	proto.RegisterEnum("Operation", Operation_name, Operation_value)
	proto.RegisterEnum("T", T_name, T_value)
	proto.RegisterType((*KV)(nil), "KV")
	proto.RegisterType((*Do)(nil), "Do")
}

func init() { proto.RegisterFile("proto_common/proto_common.proto", fileDescriptor_3f3ad5992816bccd) }

var fileDescriptor_3f3ad5992816bccd = []byte{
	// 309 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0xd0, 0xc1, 0x4f, 0xfa, 0x30,
	0x14, 0x07, 0x70, 0xba, 0x31, 0x18, 0x8f, 0xdf, 0x0f, 0xeb, 0x8b, 0x87, 0xc5, 0x8b, 0x84, 0x83,
	0x21, 0xc4, 0x0c, 0x83, 0xc6, 0xc4, 0x23, 0xb0, 0x6a, 0x88, 0x0b, 0x33, 0x65, 0x7a, 0xf0, 0x42,
	0x36, 0xda, 0xe8, 0x22, 0x50, 0x82, 0x63, 0x86, 0xff, 0xde, 0x74, 0x55, 0xa2, 0xb7, 0xf7, 0xfd,
	0x34, 0xdf, 0xd7, 0xe4, 0xc1, 0xd9, 0x66, 0xab, 0x72, 0x35, 0x5f, 0xa8, 0xd5, 0x4a, 0xad, 0xfb,
	0xbf, 0x83, 0x5f, 0x86, 0x4e, 0x0a, 0xd6, 0xc3, 0x33, 0x52, 0xb0, 0xdf, 0xe5, 0xde, 0x23, 0x6d,
	0xd2, 0x6d, 0x70, 0x3d, 0xe2, 0x09, 0x38, 0x45, 0xb2, 0xdc, 0x49, 0xcf, 0x2a, 0xcd, 0x04, 0xf4,
	0xc0, 0x29, 0xf2, 0xfd, 0x46, 0x7a, 0x76, 0x9b, 0x74, 0x5b, 0x03, 0xcb, 0x8f, 0xb9, 0x01, 0x3c,
	0x05, 0x57, 0x64, 0x1f, 0x49, 0xba, 0x94, 0xc2, 0xab, 0xb6, 0x49, 0xd7, 0xe5, 0x87, 0xdc, 0xb9,
	0x00, 0x2b, 0x50, 0x78, 0x0e, 0x6e, 0xb4, 0x91, 0xdb, 0x24, 0x57, 0xdb, 0xf2, 0xa3, 0xd6, 0x00,
	0x7c, 0x03, 0x99, 0x5a, 0xf3, 0xc3, 0x5b, 0xef, 0x16, 0x1a, 0x07, 0x46, 0x80, 0xda, 0x98, 0xb3,
	0x61, 0xcc, 0x68, 0x05, 0x5d, 0xa8, 0x72, 0x36, 0x0c, 0x28, 0xd1, 0xfa, 0xf4, 0x18, 0x68, 0xb5,
	0xf4, 0x1c, 0xb0, 0x90, 0xc5, 0x8c, 0xda, 0xbd, 0x4f, 0x20, 0xb1, 0x86, 0x59, 0xcc, 0x27, 0xd3,
	0x7b, 0x5a, 0xc1, 0x06, 0x38, 0x93, 0x69, 0x7c, 0x73, 0x4d, 0x09, 0x36, 0xa1, 0x7e, 0x17, 0x46,
	0x43, 0x1d, 0x2c, 0xbd, 0x6a, 0x14, 0x45, 0x21, 0xb5, 0x91, 0xc2, 0xbf, 0x59, 0x38, 0x19, 0xb3,
	0xf9, 0x77, 0xa7, 0x8a, 0x47, 0xd0, 0x34, 0x62, 0x9a, 0x0e, 0x1e, 0xc3, 0x7f, 0x03, 0x3f, 0xfd,
	0x1a, 0xb6, 0x00, 0x0c, 0x95, 0x5b, 0xea, 0xa3, 0xcb, 0x17, 0xff, 0x35, 0xcb, 0xdf, 0x76, 0xa9,
	0xbf, 0x50, 0xab, 0xbe, 0x48, 0x0a, 0x29, 0x54, 0x2e, 0x64, 0x61, 0x2e, 0xde, 0x97, 0x42, 0x64,
	0xf2, 0xcf, 0xf5, 0xd3, 0x5a, 0x99, 0xae, 0xbe, 0x02, 0x00, 0x00, 0xff, 0xff, 0x43, 0xdc, 0x0a,
	0x2e, 0xa1, 0x01, 0x00, 0x00,
}
