// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto_common/proto_common.proto

package proto_common

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Operation int32

const (
	Operation_CREATE     Operation = 0
	Operation_READ       Operation = 1
	Operation_UPDATE     Operation = 2
	Operation_DELETE     Operation = 3
	Operation_PROCESSING Operation = 4
	Operation_DONE       Operation = 5
)

var Operation_name = map[int32]string{
	0: "CREATE",
	1: "READ",
	2: "UPDATE",
	3: "DELETE",
	4: "PROCESSING",
	5: "DONE",
}

var Operation_value = map[string]int32{
	"CREATE":     0,
	"READ":       1,
	"UPDATE":     2,
	"DELETE":     3,
	"PROCESSING": 4,
	"DONE":       5,
}

func (x Operation) String() string {
	return proto.EnumName(Operation_name, int32(x))
}

func (Operation) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3f3ad5992816bccd, []int{0}
}

type T int32

const (
	// Inline with Neo types. Float is a point.
	T_STRING        T = 0
	T_INT64         T = 1
	T_FLOAT64       T = 2
	T_BOOL          T = 3
	T_SLICE_STRING  T = 4
	T_SLICE_INT64   T = 5
	T_SLICE_FLOAT64 T = 6
	T_SLICE_BOOL    T = 7
)

var T_name = map[int32]string{
	0: "STRING",
	1: "INT64",
	2: "FLOAT64",
	3: "BOOL",
	4: "SLICE_STRING",
	5: "SLICE_INT64",
	6: "SLICE_FLOAT64",
	7: "SLICE_BOOL",
}

var T_value = map[string]int32{
	"STRING":        0,
	"INT64":         1,
	"FLOAT64":       2,
	"BOOL":          3,
	"SLICE_STRING":  4,
	"SLICE_INT64":   5,
	"SLICE_FLOAT64": 6,
	"SLICE_BOOL":    7,
}

func (x T) String() string {
	return proto.EnumName(T_name, int32(x))
}

func (T) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3f3ad5992816bccd, []int{1}
}

type KV struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Vtype                T        `protobuf:"varint,3,opt,name=vtype,proto3,enum=T" json:"vtype,omitempty"`
	Disabled             bool     `protobuf:"varint,4,opt,name=disabled,proto3" json:"disabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KV) Reset()         { *m = KV{} }
func (m *KV) String() string { return proto.CompactTextString(m) }
func (*KV) ProtoMessage()    {}
func (*KV) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f3ad5992816bccd, []int{0}
}

func (m *KV) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KV.Unmarshal(m, b)
}
func (m *KV) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KV.Marshal(b, m, deterministic)
}
func (m *KV) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KV.Merge(m, src)
}
func (m *KV) XXX_Size() int {
	return xxx_messageInfo_KV.Size(m)
}
func (m *KV) XXX_DiscardUnknown() {
	xxx_messageInfo_KV.DiscardUnknown(m)
}

var xxx_messageInfo_KV proto.InternalMessageInfo

func (m *KV) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KV) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *KV) GetVtype() T {
	if m != nil {
		return m.Vtype
	}
	return T_STRING
}

func (m *KV) GetDisabled() bool {
	if m != nil {
		return m.Disabled
	}
	return false
}

type Do struct {
	Operator             Operation `protobuf:"varint,1,opt,name=Operator,proto3,enum=Operation" json:"Operator,omitempty"`
	Provider             string    `protobuf:"bytes,2,opt,name=Provider,proto3" json:"Provider,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Do) Reset()         { *m = Do{} }
func (m *Do) String() string { return proto.CompactTextString(m) }
func (*Do) ProtoMessage()    {}
func (*Do) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f3ad5992816bccd, []int{1}
}

func (m *Do) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Do.Unmarshal(m, b)
}
func (m *Do) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Do.Marshal(b, m, deterministic)
}
func (m *Do) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Do.Merge(m, src)
}
func (m *Do) XXX_Size() int {
	return xxx_messageInfo_Do.Size(m)
}
func (m *Do) XXX_DiscardUnknown() {
	xxx_messageInfo_Do.DiscardUnknown(m)
}

var xxx_messageInfo_Do proto.InternalMessageInfo

func (m *Do) GetOperator() Operation {
	if m != nil {
		return m.Operator
	}
	return Operation_CREATE
}

func (m *Do) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func init() {
	proto.RegisterEnum("Operation", Operation_name, Operation_value)
	proto.RegisterEnum("T", T_name, T_value)
	proto.RegisterType((*KV)(nil), "KV")
	proto.RegisterType((*Do)(nil), "Do")
}

func init() { proto.RegisterFile("proto_common/proto_common.proto", fileDescriptor_3f3ad5992816bccd) }

var fileDescriptor_3f3ad5992816bccd = []byte{
	// 336 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0xcf, 0x4f, 0xea, 0x40,
	0x10, 0xc7, 0xd9, 0xfe, 0x80, 0x32, 0xbc, 0xc7, 0xdb, 0xb7, 0xf1, 0xd0, 0x78, 0x91, 0x70, 0x30,
	0x84, 0x43, 0x31, 0x68, 0xbc, 0x03, 0x5d, 0x95, 0xd8, 0x50, 0xb2, 0xad, 0x1e, 0xbc, 0x90, 0x96,
	0xdd, 0x68, 0x23, 0xb0, 0xa4, 0x96, 0x1a, 0xfe, 0x7b, 0xb3, 0x5d, 0x6c, 0xf4, 0x36, 0x9f, 0xcf,
	0xec, 0x77, 0x66, 0x93, 0x81, 0x8b, 0x7d, 0x2e, 0x0b, 0xb9, 0x5a, 0xcb, 0xed, 0x56, 0xee, 0x46,
	0x3f, 0xc1, 0xab, 0xa0, 0x9f, 0x82, 0xf1, 0xf8, 0x4c, 0x30, 0x98, 0xef, 0xe2, 0xe8, 0xa2, 0x1e,
	0x1a, 0xb4, 0x99, 0x2a, 0xc9, 0x19, 0xd8, 0x65, 0xb2, 0x39, 0x08, 0xd7, 0xa8, 0x9c, 0x06, 0xe2,
	0x82, 0x5d, 0x16, 0xc7, 0xbd, 0x70, 0xcd, 0x1e, 0x1a, 0x74, 0xc7, 0x86, 0x17, 0x33, 0x2d, 0xc8,
	0x39, 0x38, 0x3c, 0xfb, 0x48, 0xd2, 0x8d, 0xe0, 0xae, 0xd5, 0x43, 0x03, 0x87, 0xd5, 0xdc, 0x7f,
	0x00, 0xc3, 0x97, 0xe4, 0x12, 0x9c, 0x70, 0x2f, 0xf2, 0xa4, 0x90, 0x79, 0xb5, 0xa8, 0x3b, 0x06,
	0x4f, 0x8b, 0x4c, 0xee, 0x58, 0xdd, 0x53, 0x93, 0x96, 0xb9, 0x2c, 0x33, 0x2e, 0xf2, 0xd3, 0xf2,
	0x9a, 0x87, 0x11, 0xb4, 0xeb, 0x08, 0x01, 0x68, 0xce, 0x18, 0x9d, 0xc4, 0x14, 0x37, 0x88, 0x03,
	0x16, 0xa3, 0x13, 0x1f, 0x23, 0x65, 0x9f, 0x96, 0xbe, 0xb2, 0x86, 0xaa, 0x7d, 0x1a, 0xd0, 0x98,
	0x62, 0x93, 0x74, 0x01, 0x96, 0x2c, 0x9c, 0xd1, 0x28, 0x9a, 0x2f, 0xee, 0xb1, 0xa5, 0x12, 0x7e,
	0xb8, 0xa0, 0xd8, 0x1e, 0x7e, 0x02, 0x8a, 0xd5, 0xd3, 0x28, 0x66, 0xaa, 0xd5, 0x20, 0x6d, 0xb0,
	0xe7, 0x8b, 0xf8, 0xf6, 0x06, 0x23, 0xd2, 0x81, 0xd6, 0x5d, 0x10, 0x4e, 0x14, 0x18, 0x2a, 0x32,
	0x0d, 0xc3, 0x00, 0x9b, 0x04, 0xc3, 0x9f, 0x28, 0x98, 0xcf, 0xe8, 0xea, 0x94, 0xb1, 0xc8, 0x3f,
	0xe8, 0x68, 0xa3, 0x93, 0x36, 0xf9, 0x0f, 0x7f, 0xb5, 0xf8, 0xce, 0x37, 0xd5, 0x17, 0xb4, 0xaa,
	0xa6, 0xb4, 0xa6, 0x57, 0x2f, 0xde, 0x6b, 0x56, 0xbc, 0x1d, 0x52, 0x6f, 0x2d, 0xb7, 0x23, 0x9e,
	0x94, 0x82, 0xcb, 0x82, 0x8b, 0x52, 0xdf, 0x69, 0x24, 0x38, 0xcf, 0xc4, 0xaf, 0x9b, 0xa5, 0xcd,
	0x8a, 0xae, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0x0e, 0x67, 0x9b, 0x53, 0xd7, 0x01, 0x00, 0x00,
}
