// This file contains an inventory PB for a device

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.6.1
// source: proto_common/proto_common.proto

package proto_common

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Operation int32

const (
	Operation_CREATE          Operation = 0
	Operation_READ            Operation = 1
	Operation_UPDATE          Operation = 2
	Operation_DELETE          Operation = 3
	Operation_DELETE_FULL     Operation = 4
	Operation_PROCESSING      Operation = 5
	Operation_DONE            Operation = 6
	Operation_READY           Operation = 7
	Operation_NOTHING_TO_DO   Operation = 8
	Operation_READ_NODE_BY_ID Operation = 9
)

// Enum value maps for Operation.
var (
	Operation_name = map[int32]string{
		0: "CREATE",
		1: "READ",
		2: "UPDATE",
		3: "DELETE",
		4: "DELETE_FULL",
		5: "PROCESSING",
		6: "DONE",
		7: "READY",
		8: "NOTHING_TO_DO",
		9: "READ_NODE_BY_ID",
	}
	Operation_value = map[string]int32{
		"CREATE":          0,
		"READ":            1,
		"UPDATE":          2,
		"DELETE":          3,
		"DELETE_FULL":     4,
		"PROCESSING":      5,
		"DONE":            6,
		"READY":           7,
		"NOTHING_TO_DO":   8,
		"READ_NODE_BY_ID": 9,
	}
)

func (x Operation) Enum() *Operation {
	p := new(Operation)
	*p = x
	return p
}

func (x Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_common_proto_common_proto_enumTypes[0].Descriptor()
}

func (Operation) Type() protoreflect.EnumType {
	return &file_proto_common_proto_common_proto_enumTypes[0]
}

func (x Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Operation.Descriptor instead.
func (Operation) EnumDescriptor() ([]byte, []int) {
	return file_proto_common_proto_common_proto_rawDescGZIP(), []int{0}
}

type T int32

const (
	// Inline with Neo types. Float is a point.
	T_STRING        T = 0
	T_INT64         T = 1
	T_FLOAT64       T = 2
	T_BOOL          T = 3
	T_SLICE_STRING  T = 4
	T_SLICE_INT64   T = 5
	T_SLICE_FLOAT64 T = 6
	T_SLICE_BOOL    T = 7
)

// Enum value maps for T.
var (
	T_name = map[int32]string{
		0: "STRING",
		1: "INT64",
		2: "FLOAT64",
		3: "BOOL",
		4: "SLICE_STRING",
		5: "SLICE_INT64",
		6: "SLICE_FLOAT64",
		7: "SLICE_BOOL",
	}
	T_value = map[string]int32{
		"STRING":        0,
		"INT64":         1,
		"FLOAT64":       2,
		"BOOL":          3,
		"SLICE_STRING":  4,
		"SLICE_INT64":   5,
		"SLICE_FLOAT64": 6,
		"SLICE_BOOL":    7,
	}
)

func (x T) Enum() *T {
	p := new(T)
	*p = x
	return p
}

func (x T) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (T) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_common_proto_common_proto_enumTypes[1].Descriptor()
}

func (T) Type() protoreflect.EnumType {
	return &file_proto_common_proto_common_proto_enumTypes[1]
}

func (x T) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use T.Descriptor instead.
func (T) EnumDescriptor() ([]byte, []int) {
	return file_proto_common_proto_common_proto_rawDescGZIP(), []int{1}
}

type KV struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key      string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value    string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Vtype    T      `protobuf:"varint,3,opt,name=vtype,proto3,enum=T" json:"vtype,omitempty"`
	Disabled bool   `protobuf:"varint,4,opt,name=disabled,proto3" json:"disabled,omitempty"`
}

func (x *KV) Reset() {
	*x = KV{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_proto_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KV) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KV) ProtoMessage() {}

func (x *KV) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KV.ProtoReflect.Descriptor instead.
func (*KV) Descriptor() ([]byte, []int) {
	return file_proto_common_proto_common_proto_rawDescGZIP(), []int{0}
}

func (x *KV) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KV) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *KV) GetVtype() T {
	if x != nil {
		return x.Vtype
	}
	return T_STRING
}

func (x *KV) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

type Do struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Operator Operation `protobuf:"varint,1,opt,name=Operator,proto3,enum=Operation" json:"Operator,omitempty"`
	Provider []string  `protobuf:"bytes,2,rep,name=Provider,proto3" json:"Provider,omitempty"`
}

func (x *Do) Reset() {
	*x = Do{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_common_proto_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Do) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Do) ProtoMessage() {}

func (x *Do) ProtoReflect() protoreflect.Message {
	mi := &file_proto_common_proto_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Do.ProtoReflect.Descriptor instead.
func (*Do) Descriptor() ([]byte, []int) {
	return file_proto_common_proto_common_proto_rawDescGZIP(), []int{1}
}

func (x *Do) GetOperator() Operation {
	if x != nil {
		return x.Operator
	}
	return Operation_CREATE
}

func (x *Do) GetProvider() []string {
	if x != nil {
		return x.Provider
	}
	return nil
}

var File_proto_common_proto_common_proto protoreflect.FileDescriptor

var file_proto_common_proto_common_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x62, 0x0a, 0x02, 0x4b, 0x56, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x18, 0x0a, 0x05, 0x76, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x02,
	0x2e, 0x54, 0x52, 0x05, 0x76, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x73,
	0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x64, 0x69, 0x73,
	0x61, 0x62, 0x6c, 0x65, 0x64, 0x22, 0x48, 0x0a, 0x02, 0x44, 0x6f, 0x12, 0x26, 0x0a, 0x08, 0x4f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0a, 0x2e,
	0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x4f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x6f, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x2a,
	0x97, 0x01, 0x0a, 0x09, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0a, 0x0a,
	0x06, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x52, 0x45, 0x41,
	0x44, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x10, 0x02, 0x12,
	0x0a, 0x0a, 0x06, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x03, 0x12, 0x0f, 0x0a, 0x0b, 0x44,
	0x45, 0x4c, 0x45, 0x54, 0x45, 0x5f, 0x46, 0x55, 0x4c, 0x4c, 0x10, 0x04, 0x12, 0x0e, 0x0a, 0x0a,
	0x50, 0x52, 0x4f, 0x43, 0x45, 0x53, 0x53, 0x49, 0x4e, 0x47, 0x10, 0x05, 0x12, 0x08, 0x0a, 0x04,
	0x44, 0x4f, 0x4e, 0x45, 0x10, 0x06, 0x12, 0x09, 0x0a, 0x05, 0x52, 0x45, 0x41, 0x44, 0x59, 0x10,
	0x07, 0x12, 0x11, 0x0a, 0x0d, 0x4e, 0x4f, 0x54, 0x48, 0x49, 0x4e, 0x47, 0x5f, 0x54, 0x4f, 0x5f,
	0x44, 0x4f, 0x10, 0x08, 0x12, 0x13, 0x0a, 0x0f, 0x52, 0x45, 0x41, 0x44, 0x5f, 0x4e, 0x4f, 0x44,
	0x45, 0x5f, 0x42, 0x59, 0x5f, 0x49, 0x44, 0x10, 0x09, 0x2a, 0x77, 0x0a, 0x01, 0x54, 0x12, 0x0a,
	0x0a, 0x06, 0x53, 0x54, 0x52, 0x49, 0x4e, 0x47, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x49, 0x4e,
	0x54, 0x36, 0x34, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x46, 0x4c, 0x4f, 0x41, 0x54, 0x36, 0x34,
	0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x42, 0x4f, 0x4f, 0x4c, 0x10, 0x03, 0x12, 0x10, 0x0a, 0x0c,
	0x53, 0x4c, 0x49, 0x43, 0x45, 0x5f, 0x53, 0x54, 0x52, 0x49, 0x4e, 0x47, 0x10, 0x04, 0x12, 0x0f,
	0x0a, 0x0b, 0x53, 0x4c, 0x49, 0x43, 0x45, 0x5f, 0x49, 0x4e, 0x54, 0x36, 0x34, 0x10, 0x05, 0x12,
	0x11, 0x0a, 0x0d, 0x53, 0x4c, 0x49, 0x43, 0x45, 0x5f, 0x46, 0x4c, 0x4f, 0x41, 0x54, 0x36, 0x34,
	0x10, 0x06, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x4c, 0x49, 0x43, 0x45, 0x5f, 0x42, 0x4f, 0x4f, 0x4c,
	0x10, 0x07, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x64, 0x61, 0x76, 0x65, 0x64, 0x6f, 0x74, 0x64, 0x65, 0x76, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x65, 0x64, 0x64, 0x69, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_common_proto_common_proto_rawDescOnce sync.Once
	file_proto_common_proto_common_proto_rawDescData = file_proto_common_proto_common_proto_rawDesc
)

func file_proto_common_proto_common_proto_rawDescGZIP() []byte {
	file_proto_common_proto_common_proto_rawDescOnce.Do(func() {
		file_proto_common_proto_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_common_proto_common_proto_rawDescData)
	})
	return file_proto_common_proto_common_proto_rawDescData
}

var file_proto_common_proto_common_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_common_proto_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_common_proto_common_proto_goTypes = []interface{}{
	(Operation)(0), // 0: Operation
	(T)(0),         // 1: T
	(*KV)(nil),     // 2: KV
	(*Do)(nil),     // 3: Do
}
var file_proto_common_proto_common_proto_depIdxs = []int32{
	1, // 0: KV.vtype:type_name -> T
	0, // 1: Do.Operator:type_name -> Operation
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_common_proto_common_proto_init() }
func file_proto_common_proto_common_proto_init() {
	if File_proto_common_proto_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_common_proto_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KV); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_common_proto_common_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Do); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_common_proto_common_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_common_proto_common_proto_goTypes,
		DependencyIndexes: file_proto_common_proto_common_proto_depIdxs,
		EnumInfos:         file_proto_common_proto_common_proto_enumTypes,
		MessageInfos:      file_proto_common_proto_common_proto_msgTypes,
	}.Build()
	File_proto_common_proto_common_proto = out.File
	file_proto_common_proto_common_proto_rawDesc = nil
	file_proto_common_proto_common_proto_goTypes = nil
	file_proto_common_proto_common_proto_depIdxs = nil
}
