// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto_uuid/proto_uuid.proto

package proto_uuid

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CODE int32

const (
	CODE_REQ CODE = 0
	CODE_RES CODE = 1
)

var CODE_name = map[int32]string{
	0: "REQ",
	1: "RES",
}

var CODE_value = map[string]int32{
	"REQ": 0,
	"RES": 1,
}

func (x CODE) String() string {
	return proto.EnumName(CODE_name, int32(x))
}

func (CODE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e58f44c694e2116f, []int{0}
}

type UUID struct {
	Operation            CODE     `protobuf:"varint,1,opt,name=Operation,proto3,enum=CODE" json:"Operation,omitempty"`
	UUID                 string   `protobuf:"bytes,2,opt,name=UUID,proto3" json:"UUID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UUID) Reset()         { *m = UUID{} }
func (m *UUID) String() string { return proto.CompactTextString(m) }
func (*UUID) ProtoMessage()    {}
func (*UUID) Descriptor() ([]byte, []int) {
	return fileDescriptor_e58f44c694e2116f, []int{0}
}

func (m *UUID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UUID.Unmarshal(m, b)
}
func (m *UUID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UUID.Marshal(b, m, deterministic)
}
func (m *UUID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UUID.Merge(m, src)
}
func (m *UUID) XXX_Size() int {
	return xxx_messageInfo_UUID.Size(m)
}
func (m *UUID) XXX_DiscardUnknown() {
	xxx_messageInfo_UUID.DiscardUnknown(m)
}

var xxx_messageInfo_UUID proto.InternalMessageInfo

func (m *UUID) GetOperation() CODE {
	if m != nil {
		return m.Operation
	}
	return CODE_REQ
}

func (m *UUID) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

func init() {
	proto.RegisterEnum("CODE", CODE_name, CODE_value)
	proto.RegisterType((*UUID)(nil), "UUID")
}

func init() { proto.RegisterFile("proto_uuid/proto_uuid.proto", fileDescriptor_e58f44c694e2116f) }

var fileDescriptor_e58f44c694e2116f = []byte{
	// 151 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2e, 0x28, 0xca, 0x2f,
	0xc9, 0x8f, 0x2f, 0x2d, 0xcd, 0x4c, 0xd1, 0x47, 0x30, 0xf5, 0xc0, 0x4c, 0x25, 0x7b, 0x2e, 0x96,
	0xd0, 0x50, 0x4f, 0x17, 0x21, 0x65, 0x2e, 0x4e, 0xff, 0x82, 0xd4, 0xa2, 0xc4, 0x92, 0xcc, 0xfc,
	0x3c, 0x09, 0x46, 0x05, 0x46, 0x0d, 0x3e, 0x23, 0x56, 0x3d, 0x67, 0x7f, 0x17, 0xd7, 0x20, 0x84,
	0xb8, 0x90, 0x10, 0x44, 0xb1, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x98, 0xad, 0x25, 0xc1,
	0xc5, 0x02, 0x52, 0x26, 0xc4, 0xce, 0xc5, 0x1c, 0xe4, 0x1a, 0x28, 0xc0, 0x00, 0x61, 0x04, 0x0b,
	0x30, 0x3a, 0xe9, 0x45, 0xe9, 0xa4, 0x67, 0x96, 0x64, 0x94, 0x26, 0xe9, 0x25, 0xe7, 0xe7, 0xea,
	0xa7, 0x24, 0x96, 0xa5, 0xa6, 0xe4, 0x97, 0xa4, 0xa4, 0x96, 0x41, 0x1c, 0xa1, 0x9f, 0x9a, 0x92,
	0x92, 0x99, 0x8a, 0xe4, 0xa0, 0x24, 0x36, 0x30, 0xdb, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xa9,
	0xfd, 0xf7, 0xba, 0xb0, 0x00, 0x00, 0x00,
}
