// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto_node/proto_node.proto

package proto_node

import (
	fmt "fmt"
	proto_common "github.com/davedotdev/proto/eddie/proto_common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NODELIST struct {
	Node                 []*NODE  `protobuf:"bytes,1,rep,name=node,proto3" json:"node,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NODELIST) Reset()         { *m = NODELIST{} }
func (m *NODELIST) String() string { return proto.CompactTextString(m) }
func (*NODELIST) ProtoMessage()    {}
func (*NODELIST) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a82cd30cca8ea4b, []int{0}
}

func (m *NODELIST) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NODELIST.Unmarshal(m, b)
}
func (m *NODELIST) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NODELIST.Marshal(b, m, deterministic)
}
func (m *NODELIST) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NODELIST.Merge(m, src)
}
func (m *NODELIST) XXX_Size() int {
	return xxx_messageInfo_NODELIST.Size(m)
}
func (m *NODELIST) XXX_DiscardUnknown() {
	xxx_messageInfo_NODELIST.DiscardUnknown(m)
}

var xxx_messageInfo_NODELIST proto.InternalMessageInfo

func (m *NODELIST) GetNode() []*NODE {
	if m != nil {
		return m.Node
	}
	return nil
}

type NODE struct {
	NodeIdentity         int64                  `protobuf:"varint,1,opt,name=NodeIdentity,proto3" json:"NodeIdentity,omitempty"`
	Type                 string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Kv                   []*proto_common.KV     `protobuf:"bytes,3,rep,name=kv,proto3" json:"kv,omitempty"`
	Updatedkv            []*proto_common.KV     `protobuf:"bytes,4,rep,name=updatedkv,proto3" json:"updatedkv,omitempty"`
	Operation            proto_common.Operation `protobuf:"varint,5,opt,name=operation,proto3,enum=Operation" json:"operation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *NODE) Reset()         { *m = NODE{} }
func (m *NODE) String() string { return proto.CompactTextString(m) }
func (*NODE) ProtoMessage()    {}
func (*NODE) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a82cd30cca8ea4b, []int{1}
}

func (m *NODE) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NODE.Unmarshal(m, b)
}
func (m *NODE) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NODE.Marshal(b, m, deterministic)
}
func (m *NODE) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NODE.Merge(m, src)
}
func (m *NODE) XXX_Size() int {
	return xxx_messageInfo_NODE.Size(m)
}
func (m *NODE) XXX_DiscardUnknown() {
	xxx_messageInfo_NODE.DiscardUnknown(m)
}

var xxx_messageInfo_NODE proto.InternalMessageInfo

func (m *NODE) GetNodeIdentity() int64 {
	if m != nil {
		return m.NodeIdentity
	}
	return 0
}

func (m *NODE) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *NODE) GetKv() []*proto_common.KV {
	if m != nil {
		return m.Kv
	}
	return nil
}

func (m *NODE) GetUpdatedkv() []*proto_common.KV {
	if m != nil {
		return m.Updatedkv
	}
	return nil
}

func (m *NODE) GetOperation() proto_common.Operation {
	if m != nil {
		return m.Operation
	}
	return proto_common.Operation_CREATE
}

func init() {
	proto.RegisterType((*NODELIST)(nil), "NODELIST")
	proto.RegisterType((*NODE)(nil), "NODE")
}

func init() { proto.RegisterFile("proto_node/proto_node.proto", fileDescriptor_5a82cd30cca8ea4b) }

var fileDescriptor_5a82cd30cca8ea4b = []byte{
	// 238 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0x49, 0xdb, 0x15, 0x3b, 0x8a, 0x87, 0x78, 0x89, 0x7a, 0xb0, 0x16, 0x84, 0x1c, 0x24,
	0x85, 0xf5, 0x0d, 0x44, 0x0f, 0x8b, 0xb2, 0x0b, 0x51, 0x3c, 0x78, 0x91, 0xee, 0xce, 0xa0, 0xa5,
	0xb4, 0x53, 0x96, 0x6c, 0x60, 0xdf, 0xc6, 0x47, 0x95, 0xa6, 0x48, 0xd6, 0xdb, 0xf7, 0x7f, 0x7f,
	0x32, 0x30, 0x03, 0x57, 0xc3, 0x96, 0x1d, 0x7f, 0xf6, 0x8c, 0x54, 0x45, 0x34, 0x01, 0x2f, 0xaf,
	0x27, 0xb3, 0xe1, 0xae, 0xe3, 0xbe, 0x3a, 0x0c, 0xd3, 0x83, 0xf2, 0x16, 0x8e, 0x97, 0xab, 0xc7,
	0xa7, 0x97, 0xc5, 0xeb, 0x9b, 0xbc, 0x80, 0x6c, 0xfc, 0xaa, 0x44, 0x91, 0xea, 0x93, 0xf9, 0xcc,
	0x8c, 0x85, 0x0d, 0xaa, 0xfc, 0x11, 0x90, 0x8d, 0x51, 0x96, 0x70, 0xba, 0x64, 0xa4, 0x05, 0x52,
	0xef, 0x1a, 0xb7, 0x57, 0xa2, 0x10, 0x3a, 0xb5, 0xff, 0x9c, 0x94, 0x90, 0xb9, 0xfd, 0x40, 0x2a,
	0x29, 0x84, 0xce, 0x6d, 0x60, 0x79, 0x0e, 0x49, 0xeb, 0x55, 0x1a, 0x26, 0xa7, 0xe6, 0xf9, 0xdd,
	0x26, 0xad, 0x97, 0x37, 0x90, 0xef, 0x06, 0xac, 0x1d, 0x61, 0xeb, 0x55, 0x16, 0xbb, 0x68, 0xa5,
	0x86, 0x9c, 0x07, 0xda, 0xd6, 0xae, 0xe1, 0x5e, 0xcd, 0x0a, 0xa1, 0xcf, 0xe6, 0x60, 0x56, 0x7f,
	0xc6, 0xc6, 0xf2, 0xc1, 0x7c, 0xdc, 0x7d, 0x35, 0xee, 0x7b, 0xb7, 0x36, 0x1b, 0xee, 0x2a, 0xac,
	0x3d, 0x21, 0x3b, 0x24, 0x3f, 0x6d, 0x5d, 0x11, 0x62, 0x73, 0x78, 0xa0, 0xf5, 0x51, 0xe0, 0xfb,
	0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf5, 0x07, 0x32, 0x1d, 0x40, 0x01, 0x00, 0x00,
}
