// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto_inventory/proto_inventory.proto

package proto_inventory

import (
	fmt "fmt"
	proto_common "github.com/davedotdev/edmund/proto_common"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DEVICE struct {
	Name                 string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Vendor               string                 `protobuf:"bytes,2,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Platform             string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	Routeengine          []*RouteEngine         `protobuf:"bytes,4,rep,name=routeengine,proto3" json:"routeengine,omitempty"`
	Linecard             []*Linecard            `protobuf:"bytes,5,rep,name=linecard,proto3" json:"linecard,omitempty"`
	Operation            proto_common.Operation `protobuf:"varint,6,opt,name=operation,proto3,enum=Operation" json:"operation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *DEVICE) Reset()         { *m = DEVICE{} }
func (m *DEVICE) String() string { return proto.CompactTextString(m) }
func (*DEVICE) ProtoMessage()    {}
func (*DEVICE) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd0852c13d032805, []int{0}
}

func (m *DEVICE) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DEVICE.Unmarshal(m, b)
}
func (m *DEVICE) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DEVICE.Marshal(b, m, deterministic)
}
func (m *DEVICE) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DEVICE.Merge(m, src)
}
func (m *DEVICE) XXX_Size() int {
	return xxx_messageInfo_DEVICE.Size(m)
}
func (m *DEVICE) XXX_DiscardUnknown() {
	xxx_messageInfo_DEVICE.DiscardUnknown(m)
}

var xxx_messageInfo_DEVICE proto.InternalMessageInfo

func (m *DEVICE) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DEVICE) GetVendor() string {
	if m != nil {
		return m.Vendor
	}
	return ""
}

func (m *DEVICE) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *DEVICE) GetRouteengine() []*RouteEngine {
	if m != nil {
		return m.Routeengine
	}
	return nil
}

func (m *DEVICE) GetLinecard() []*Linecard {
	if m != nil {
		return m.Linecard
	}
	return nil
}

func (m *DEVICE) GetOperation() proto_common.Operation {
	if m != nil {
		return m.Operation
	}
	return proto_common.Operation_CREATE
}

type Linecard struct {
	Slot                 uint32                 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	Model                string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	PortType             string                 `protobuf:"bytes,3,opt,name=portType,proto3" json:"portType,omitempty"`
	Ports                uint32                 `protobuf:"varint,4,opt,name=ports,proto3" json:"ports,omitempty"`
	Explicit             bool                   `protobuf:"varint,5,opt,name=explicit,proto3" json:"explicit,omitempty"`
	Operation            proto_common.Operation `protobuf:"varint,6,opt,name=operation,proto3,enum=Operation" json:"operation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Linecard) Reset()         { *m = Linecard{} }
func (m *Linecard) String() string { return proto.CompactTextString(m) }
func (*Linecard) ProtoMessage()    {}
func (*Linecard) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd0852c13d032805, []int{1}
}

func (m *Linecard) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Linecard.Unmarshal(m, b)
}
func (m *Linecard) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Linecard.Marshal(b, m, deterministic)
}
func (m *Linecard) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Linecard.Merge(m, src)
}
func (m *Linecard) XXX_Size() int {
	return xxx_messageInfo_Linecard.Size(m)
}
func (m *Linecard) XXX_DiscardUnknown() {
	xxx_messageInfo_Linecard.DiscardUnknown(m)
}

var xxx_messageInfo_Linecard proto.InternalMessageInfo

func (m *Linecard) GetSlot() uint32 {
	if m != nil {
		return m.Slot
	}
	return 0
}

func (m *Linecard) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *Linecard) GetPortType() string {
	if m != nil {
		return m.PortType
	}
	return ""
}

func (m *Linecard) GetPorts() uint32 {
	if m != nil {
		return m.Ports
	}
	return 0
}

func (m *Linecard) GetExplicit() bool {
	if m != nil {
		return m.Explicit
	}
	return false
}

func (m *Linecard) GetOperation() proto_common.Operation {
	if m != nil {
		return m.Operation
	}
	return proto_common.Operation_CREATE
}

type RouteEngine struct {
	Slot                 uint32                 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	Model                string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	MgmtIf               string                 `protobuf:"bytes,3,opt,name=mgmt_if,json=mgmtIf,proto3" json:"mgmt_if,omitempty"`
	Operation            proto_common.Operation `protobuf:"varint,4,opt,name=operation,proto3,enum=Operation" json:"operation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *RouteEngine) Reset()         { *m = RouteEngine{} }
func (m *RouteEngine) String() string { return proto.CompactTextString(m) }
func (*RouteEngine) ProtoMessage()    {}
func (*RouteEngine) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd0852c13d032805, []int{2}
}

func (m *RouteEngine) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RouteEngine.Unmarshal(m, b)
}
func (m *RouteEngine) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RouteEngine.Marshal(b, m, deterministic)
}
func (m *RouteEngine) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RouteEngine.Merge(m, src)
}
func (m *RouteEngine) XXX_Size() int {
	return xxx_messageInfo_RouteEngine.Size(m)
}
func (m *RouteEngine) XXX_DiscardUnknown() {
	xxx_messageInfo_RouteEngine.DiscardUnknown(m)
}

var xxx_messageInfo_RouteEngine proto.InternalMessageInfo

func (m *RouteEngine) GetSlot() uint32 {
	if m != nil {
		return m.Slot
	}
	return 0
}

func (m *RouteEngine) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *RouteEngine) GetMgmtIf() string {
	if m != nil {
		return m.MgmtIf
	}
	return ""
}

func (m *RouteEngine) GetOperation() proto_common.Operation {
	if m != nil {
		return m.Operation
	}
	return proto_common.Operation_CREATE
}

func init() {
	proto.RegisterType((*DEVICE)(nil), "DEVICE")
	proto.RegisterType((*Linecard)(nil), "Linecard")
	proto.RegisterType((*RouteEngine)(nil), "RouteEngine")
}

func init() {
	proto.RegisterFile("proto_inventory/proto_inventory.proto", fileDescriptor_fd0852c13d032805)
}

var fileDescriptor_fd0852c13d032805 = []byte{
	// 336 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xcf, 0x4a, 0xeb, 0x40,
	0x14, 0xc6, 0xc9, 0x6d, 0x9a, 0x9b, 0x4e, 0xef, 0x75, 0x31, 0x88, 0x0e, 0xdd, 0x18, 0x0a, 0x85,
	0x2c, 0x24, 0x81, 0xfa, 0x06, 0x6a, 0x17, 0x05, 0x41, 0x18, 0xc4, 0x85, 0x9b, 0x92, 0x66, 0x4e,
	0xeb, 0x40, 0x66, 0x4e, 0x98, 0x4e, 0x83, 0xf5, 0x99, 0x7c, 0x19, 0xdf, 0x48, 0x32, 0x49, 0x63,
	0xed, 0x42, 0xe8, 0xee, 0xfc, 0xbe, 0xf3, 0xf7, 0x1b, 0x86, 0x4c, 0x4a, 0x83, 0x16, 0x17, 0x52,
	0x57, 0xa0, 0x2d, 0x9a, 0x5d, 0x7a, 0xc4, 0x89, 0xe3, 0xd1, 0x55, 0x23, 0xe7, 0xa8, 0x14, 0xea,
	0xf4, 0x10, 0x9a, 0x82, 0xf1, 0xa7, 0x47, 0x82, 0xfb, 0xd9, 0xf3, 0xfc, 0x6e, 0x46, 0x29, 0xf1,
	0x75, 0xa6, 0x80, 0x79, 0x91, 0x17, 0x0f, 0xb8, 0x8b, 0xe9, 0x05, 0x09, 0x2a, 0xd0, 0x02, 0x0d,
	0xfb, 0xe3, 0xd4, 0x96, 0xe8, 0x88, 0x84, 0x65, 0x91, 0xd9, 0x15, 0x1a, 0xc5, 0x7a, 0x2e, 0xd3,
	0x31, 0x4d, 0xc8, 0xd0, 0xe0, 0xd6, 0x02, 0xe8, 0xb5, 0xd4, 0xc0, 0xfc, 0xa8, 0x17, 0x0f, 0xa7,
	0xff, 0x12, 0x5e, 0x6b, 0x33, 0xa7, 0xf1, 0xc3, 0x02, 0x3a, 0x21, 0x61, 0x21, 0x35, 0xe4, 0x99,
	0x11, 0xac, 0xef, 0x8a, 0x07, 0xc9, 0x43, 0x2b, 0xf0, 0x2e, 0x45, 0x63, 0x32, 0xc0, 0x12, 0x4c,
	0x66, 0x25, 0x6a, 0x16, 0x44, 0x5e, 0x7c, 0x36, 0x25, 0xc9, 0xe3, 0x5e, 0xe1, 0xdf, 0xc9, 0xf1,
	0x87, 0x47, 0xc2, 0xfd, 0x80, 0xda, 0xd5, 0xa6, 0x40, 0xeb, 0x5c, 0xfd, 0xe7, 0x2e, 0xa6, 0xe7,
	0xa4, 0xaf, 0x50, 0x40, 0xd1, 0x9a, 0x6a, 0xc0, 0x79, 0x42, 0x63, 0x9f, 0x76, 0x25, 0x74, 0x9e,
	0x5a, 0xae, 0x3b, 0xea, 0x78, 0xc3, 0x7c, 0x37, 0xa6, 0x81, 0xba, 0x03, 0xde, 0xca, 0x42, 0xe6,
	0xd2, 0xb2, 0x7e, 0xe4, 0xc5, 0x21, 0xef, 0xf8, 0x84, 0x73, 0xdf, 0xc9, 0xf0, 0xe0, 0x6d, 0x4e,
	0x38, 0xf8, 0x92, 0xfc, 0x55, 0x6b, 0x65, 0x17, 0x72, 0xd5, 0xde, 0x1b, 0xd4, 0x38, 0x5f, 0xfd,
	0xdc, 0xed, 0xff, 0xb2, 0xfb, 0x36, 0x79, 0xb9, 0x5e, 0x4b, 0xfb, 0xba, 0x5d, 0x26, 0x39, 0xaa,
	0x54, 0x64, 0x15, 0x08, 0xb4, 0x02, 0xaa, 0x14, 0x84, 0xda, 0x6a, 0x71, 0xfc, 0xab, 0x96, 0x81,
	0x13, 0x6e, 0xbe, 0x02, 0x00, 0x00, 0xff, 0xff, 0x3f, 0x27, 0xde, 0xb3, 0x7f, 0x02, 0x00, 0x00,
}
