// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto_resource_model/proto_resource_model.proto

package proto_resource_model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type State int32

const (
	State_MODELCREATE  State = 0
	State_MODELCREATED State = 1
	State_MODELDELETE  State = 2
	State_MODELDELETED State = 3
	State_MODELERROR   State = 4
	State_JOBINIT      State = 5
	State_JOBPLAN      State = 6
	State_JOBAPPROVE   State = 7
	State_JOBAPPROVED  State = 8
	State_JOBDEPLOY    State = 9
	State_JOBDEPLOYED  State = 10
	State_JOBERROR     State = 11
)

var State_name = map[int32]string{
	0:  "MODELCREATE",
	1:  "MODELCREATED",
	2:  "MODELDELETE",
	3:  "MODELDELETED",
	4:  "MODELERROR",
	5:  "JOBINIT",
	6:  "JOBPLAN",
	7:  "JOBAPPROVE",
	8:  "JOBAPPROVED",
	9:  "JOBDEPLOY",
	10: "JOBDEPLOYED",
	11: "JOBERROR",
}

var State_value = map[string]int32{
	"MODELCREATE":  0,
	"MODELCREATED": 1,
	"MODELDELETE":  2,
	"MODELDELETED": 3,
	"MODELERROR":   4,
	"JOBINIT":      5,
	"JOBPLAN":      6,
	"JOBAPPROVE":   7,
	"JOBAPPROVED":  8,
	"JOBDEPLOY":    9,
	"JOBDEPLOYED":  10,
	"JOBERROR":     11,
}

func (x State) String() string {
	return proto.EnumName(State_name, int32(x))
}

func (State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4fb3e7660cb4a0b9, []int{0}
}

type MetaType int32

const (
	MetaType_GRAPH MetaType = 0
	MetaType_JOB   MetaType = 1
)

var MetaType_name = map[int32]string{
	0: "GRAPH",
	1: "JOB",
}

var MetaType_value = map[string]int32{
	"GRAPH": 0,
	"JOB":   1,
}

func (x MetaType) String() string {
	return proto.EnumName(MetaType_name, int32(x))
}

func (MetaType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4fb3e7660cb4a0b9, []int{1}
}

type Plans struct {
	CFGPlanURL           string   `protobuf:"bytes,1,opt,name=CFGPlanURL,proto3" json:"CFGPlanURL,omitempty"`
	TFPlanURL            string   `protobuf:"bytes,2,opt,name=TFPlanURL,proto3" json:"TFPlanURL,omitempty"`
	UUID                 string   `protobuf:"bytes,3,opt,name=UUID,proto3" json:"UUID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Plans) Reset()         { *m = Plans{} }
func (m *Plans) String() string { return proto.CompactTextString(m) }
func (*Plans) ProtoMessage()    {}
func (*Plans) Descriptor() ([]byte, []int) {
	return fileDescriptor_4fb3e7660cb4a0b9, []int{0}
}

func (m *Plans) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Plans.Unmarshal(m, b)
}
func (m *Plans) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Plans.Marshal(b, m, deterministic)
}
func (m *Plans) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Plans.Merge(m, src)
}
func (m *Plans) XXX_Size() int {
	return xxx_messageInfo_Plans.Size(m)
}
func (m *Plans) XXX_DiscardUnknown() {
	xxx_messageInfo_Plans.DiscardUnknown(m)
}

var xxx_messageInfo_Plans proto.InternalMessageInfo

func (m *Plans) GetCFGPlanURL() string {
	if m != nil {
		return m.CFGPlanURL
	}
	return ""
}

func (m *Plans) GetTFPlanURL() string {
	if m != nil {
		return m.TFPlanURL
	}
	return ""
}

func (m *Plans) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

type History struct {
	Time                 string   `protobuf:"bytes,1,opt,name=Time,proto3" json:"Time,omitempty"`
	State                State    `protobuf:"varint,2,opt,name=State,proto3,enum=State" json:"State,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	Username             string   `protobuf:"bytes,4,opt,name=Username,proto3" json:"Username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *History) Reset()         { *m = History{} }
func (m *History) String() string { return proto.CompactTextString(m) }
func (*History) ProtoMessage()    {}
func (*History) Descriptor() ([]byte, []int) {
	return fileDescriptor_4fb3e7660cb4a0b9, []int{1}
}

func (m *History) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_History.Unmarshal(m, b)
}
func (m *History) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_History.Marshal(b, m, deterministic)
}
func (m *History) XXX_Merge(src proto.Message) {
	xxx_messageInfo_History.Merge(m, src)
}
func (m *History) XXX_Size() int {
	return xxx_messageInfo_History.Size(m)
}
func (m *History) XXX_DiscardUnknown() {
	xxx_messageInfo_History.DiscardUnknown(m)
}

var xxx_messageInfo_History proto.InternalMessageInfo

func (m *History) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *History) GetState() State {
	if m != nil {
		return m.State
	}
	return State_MODELCREATE
}

func (m *History) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *History) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type TFMeta struct {
	State                State      `protobuf:"varint,1,opt,name=State,proto3,enum=State" json:"State,omitempty"`
	MetaType             MetaType   `protobuf:"varint,2,opt,name=MetaType,proto3,enum=MetaType" json:"MetaType,omitempty"`
	Device               string     `protobuf:"bytes,3,opt,name=Device,proto3" json:"Device,omitempty"`
	ProviderName         string     `protobuf:"bytes,4,opt,name=ProviderName,proto3" json:"ProviderName,omitempty"`
	ResourceName         string     `protobuf:"bytes,5,opt,name=ResourceName,proto3" json:"ResourceName,omitempty"`
	TransactionUUID      string     `protobuf:"bytes,6,opt,name=TransactionUUID,proto3" json:"TransactionUUID,omitempty"`
	Description          string     `protobuf:"bytes,7,opt,name=Description,proto3" json:"Description,omitempty"`
	Plans                []*Plans   `protobuf:"bytes,8,rep,name=Plans,proto3" json:"Plans,omitempty"`
	History              []*History `protobuf:"bytes,9,rep,name=History,proto3" json:"History,omitempty"`
	Hash                 string     `protobuf:"bytes,10,opt,name=Hash,proto3" json:"Hash,omitempty"`
	Payload              string     `protobuf:"bytes,11,opt,name=Payload,proto3" json:"Payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *TFMeta) Reset()         { *m = TFMeta{} }
func (m *TFMeta) String() string { return proto.CompactTextString(m) }
func (*TFMeta) ProtoMessage()    {}
func (*TFMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_4fb3e7660cb4a0b9, []int{2}
}

func (m *TFMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TFMeta.Unmarshal(m, b)
}
func (m *TFMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TFMeta.Marshal(b, m, deterministic)
}
func (m *TFMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TFMeta.Merge(m, src)
}
func (m *TFMeta) XXX_Size() int {
	return xxx_messageInfo_TFMeta.Size(m)
}
func (m *TFMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_TFMeta.DiscardUnknown(m)
}

var xxx_messageInfo_TFMeta proto.InternalMessageInfo

func (m *TFMeta) GetState() State {
	if m != nil {
		return m.State
	}
	return State_MODELCREATE
}

func (m *TFMeta) GetMetaType() MetaType {
	if m != nil {
		return m.MetaType
	}
	return MetaType_GRAPH
}

func (m *TFMeta) GetDevice() string {
	if m != nil {
		return m.Device
	}
	return ""
}

func (m *TFMeta) GetProviderName() string {
	if m != nil {
		return m.ProviderName
	}
	return ""
}

func (m *TFMeta) GetResourceName() string {
	if m != nil {
		return m.ResourceName
	}
	return ""
}

func (m *TFMeta) GetTransactionUUID() string {
	if m != nil {
		return m.TransactionUUID
	}
	return ""
}

func (m *TFMeta) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *TFMeta) GetPlans() []*Plans {
	if m != nil {
		return m.Plans
	}
	return nil
}

func (m *TFMeta) GetHistory() []*History {
	if m != nil {
		return m.History
	}
	return nil
}

func (m *TFMeta) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *TFMeta) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

func init() {
	proto.RegisterEnum("State", State_name, State_value)
	proto.RegisterEnum("MetaType", MetaType_name, MetaType_value)
	proto.RegisterType((*Plans)(nil), "Plans")
	proto.RegisterType((*History)(nil), "History")
	proto.RegisterType((*TFMeta)(nil), "TFMeta")
}

func init() {
	proto.RegisterFile("proto_resource_model/proto_resource_model.proto", fileDescriptor_4fb3e7660cb4a0b9)
}

var fileDescriptor_4fb3e7660cb4a0b9 = []byte{
	// 500 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x93, 0xdf, 0x6a, 0xdb, 0x30,
	0x14, 0xc6, 0xeb, 0x26, 0xf1, 0x9f, 0xe3, 0xac, 0x15, 0xba, 0x18, 0x66, 0x84, 0x12, 0x02, 0x83,
	0xd0, 0x0b, 0x07, 0x3a, 0x18, 0xbb, 0x8d, 0x2b, 0xa5, 0x49, 0x48, 0x63, 0xa3, 0x39, 0x83, 0xee,
	0xa6, 0xa8, 0xb1, 0x58, 0x0d, 0x49, 0x14, 0x6c, 0x37, 0x90, 0x17, 0xdc, 0xbb, 0xec, 0x2d, 0x86,
	0x65, 0x25, 0xf1, 0xba, 0xdc, 0x9d, 0xef, 0xf7, 0x7d, 0x1c, 0xc9, 0xe7, 0x58, 0x30, 0xd8, 0x66,
	0xb2, 0x90, 0xcf, 0x99, 0xc8, 0xe5, 0x5b, 0xb6, 0x14, 0xcf, 0x6b, 0x99, 0x88, 0xd5, 0x59, 0xe8,
	0x2b, 0xd8, 0x7b, 0x82, 0x56, 0xb4, 0xe2, 0x9b, 0x1c, 0xdf, 0x00, 0xdc, 0x8f, 0x1e, 0xca, 0x7a,
	0xc1, 0x66, 0x9e, 0xd1, 0x35, 0xfa, 0x0e, 0xab, 0x11, 0xdc, 0x01, 0x27, 0x1e, 0x1d, 0xec, 0x4b,
	0x65, 0x9f, 0x00, 0xc6, 0xd0, 0x5c, 0x2c, 0x26, 0xc4, 0x6b, 0x28, 0x43, 0xd5, 0xbd, 0x3d, 0x58,
	0xe3, 0x34, 0x2f, 0x64, 0xb6, 0x2f, 0xed, 0x38, 0x5d, 0x0b, 0xdd, 0x56, 0xd5, 0xb8, 0x03, 0xad,
	0xef, 0x05, 0x2f, 0x84, 0x6a, 0x76, 0x75, 0x67, 0xfa, 0x4a, 0xb1, 0x0a, 0xe2, 0x2e, 0xb8, 0x44,
	0xe4, 0xcb, 0x2c, 0xdd, 0x16, 0xa9, 0xdc, 0xe8, 0xbe, 0x75, 0x84, 0x3f, 0x81, 0xbd, 0xc8, 0x45,
	0xb6, 0xe1, 0x6b, 0xe1, 0x35, 0x95, 0x7d, 0xd4, 0xbd, 0x3f, 0x97, 0x60, 0xc6, 0xa3, 0x47, 0x51,
	0xf0, 0xd3, 0x31, 0xc6, 0xb9, 0x63, 0x3e, 0x83, 0x5d, 0xa6, 0xe2, 0xfd, 0xf6, 0x70, 0x0f, 0xc7,
	0x3f, 0x00, 0x76, 0xb4, 0xf0, 0x47, 0x30, 0x89, 0xd8, 0xa5, 0x4b, 0xa1, 0x2f, 0xa2, 0x15, 0xee,
	0x41, 0x3b, 0xca, 0xe4, 0x2e, 0x4d, 0x44, 0x36, 0x3f, 0xdd, 0xe3, 0x1f, 0x56, 0x66, 0x98, 0x9e,
	0xbc, 0xca, 0xb4, 0xaa, 0x4c, 0x9d, 0xe1, 0x3e, 0x5c, 0xc7, 0x19, 0xdf, 0xe4, 0x7c, 0x59, 0x7e,
	0x9a, 0x9a, 0xa4, 0xa9, 0x62, 0xef, 0xf1, 0xfb, 0xb9, 0x58, 0xff, 0xcf, 0xa5, 0xa3, 0x37, 0xea,
	0xd9, 0xdd, 0x46, 0xdf, 0xbd, 0x33, 0x7d, 0xa5, 0x98, 0x5e, 0x73, 0xef, 0xb8, 0x14, 0xcf, 0x51,
	0xbe, 0xed, 0x6b, 0xcd, 0xea, 0xdb, 0x1a, 0xf3, 0xfc, 0xd5, 0x83, 0x6a, 0x5b, 0x65, 0x8d, 0x3d,
	0xb0, 0x22, 0xbe, 0x5f, 0x49, 0x9e, 0x78, 0xae, 0xc2, 0x07, 0x79, 0xfb, 0xdb, 0xd0, 0x13, 0xc6,
	0xd7, 0xe0, 0x3e, 0x86, 0x84, 0xce, 0xee, 0x19, 0x1d, 0xc6, 0x14, 0x5d, 0x60, 0x04, 0xed, 0x1a,
	0x20, 0xc8, 0x38, 0x46, 0x08, 0x9d, 0xd1, 0x98, 0xa2, 0xcb, 0x63, 0xa4, 0x02, 0x04, 0x35, 0xf0,
	0x15, 0x80, 0x22, 0x94, 0xb1, 0x90, 0xa1, 0x26, 0x76, 0xc1, 0x9a, 0x86, 0xc1, 0x64, 0x3e, 0x89,
	0x51, 0x4b, 0x8b, 0x68, 0x36, 0x9c, 0x23, 0xb3, 0x4c, 0x4e, 0xc3, 0x60, 0x18, 0x45, 0x2c, 0xfc,
	0x41, 0x91, 0x55, 0x36, 0x3f, 0x69, 0x82, 0x6c, 0xfc, 0x01, 0x9c, 0x69, 0x18, 0x10, 0x1a, 0xcd,
	0xc2, 0x27, 0xe4, 0x68, 0xbf, 0x92, 0x94, 0x20, 0xc0, 0x6d, 0xb0, 0xa7, 0x61, 0x50, 0x1d, 0xe4,
	0xde, 0xde, 0x9c, 0xfe, 0x05, 0xec, 0x40, 0xeb, 0x81, 0x0d, 0xa3, 0x31, 0xba, 0xc0, 0x16, 0x34,
	0xa6, 0x61, 0x80, 0x8c, 0xe0, 0xdb, 0xcf, 0xaf, 0xbf, 0xd2, 0xe2, 0xf5, 0xed, 0xc5, 0x5f, 0xca,
	0xf5, 0x20, 0xe1, 0x3b, 0x91, 0xc8, 0x22, 0x11, 0xbb, 0xea, 0x79, 0x0d, 0x44, 0x92, 0xa4, 0xe2,
	0xec, 0x53, 0x7b, 0x31, 0x15, 0xfd, 0xf2, 0x37, 0x00, 0x00, 0xff, 0xff, 0xd4, 0x3b, 0x69, 0xc9,
	0x9e, 0x03, 0x00, 0x00,
}
