// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto_resource_model/proto_resource_model.proto

package proto_resource_model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type State int32

const (
	State_INIT      State = 0
	State_PLAN      State = 1
	State_APPROVALS State = 2
	State_DEPLOY    State = 3
	State_DEPLOYED  State = 4
	State_ERROR     State = 5
)

var State_name = map[int32]string{
	0: "INIT",
	1: "PLAN",
	2: "APPROVALS",
	3: "DEPLOY",
	4: "DEPLOYED",
	5: "ERROR",
}

var State_value = map[string]int32{
	"INIT":      0,
	"PLAN":      1,
	"APPROVALS": 2,
	"DEPLOY":    3,
	"DEPLOYED":  4,
	"ERROR":     5,
}

func (x State) String() string {
	return proto.EnumName(State_name, int32(x))
}

func (State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4fb3e7660cb4a0b9, []int{0}
}

type MetaType int32

const (
	MetaType_GRAPH MetaType = 0
	MetaType_JOB   MetaType = 1
)

var MetaType_name = map[int32]string{
	0: "GRAPH",
	1: "JOB",
}

var MetaType_value = map[string]int32{
	"GRAPH": 0,
	"JOB":   1,
}

func (x MetaType) String() string {
	return proto.EnumName(MetaType_name, int32(x))
}

func (MetaType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4fb3e7660cb4a0b9, []int{1}
}

type Plans struct {
	CFGPlanURL           string   `protobuf:"bytes,1,opt,name=CFGPlanURL,proto3" json:"CFGPlanURL,omitempty"`
	TFPlanURL            string   `protobuf:"bytes,2,opt,name=TFPlanURL,proto3" json:"TFPlanURL,omitempty"`
	UUID                 string   `protobuf:"bytes,3,opt,name=UUID,proto3" json:"UUID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Plans) Reset()         { *m = Plans{} }
func (m *Plans) String() string { return proto.CompactTextString(m) }
func (*Plans) ProtoMessage()    {}
func (*Plans) Descriptor() ([]byte, []int) {
	return fileDescriptor_4fb3e7660cb4a0b9, []int{0}
}

func (m *Plans) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Plans.Unmarshal(m, b)
}
func (m *Plans) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Plans.Marshal(b, m, deterministic)
}
func (m *Plans) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Plans.Merge(m, src)
}
func (m *Plans) XXX_Size() int {
	return xxx_messageInfo_Plans.Size(m)
}
func (m *Plans) XXX_DiscardUnknown() {
	xxx_messageInfo_Plans.DiscardUnknown(m)
}

var xxx_messageInfo_Plans proto.InternalMessageInfo

func (m *Plans) GetCFGPlanURL() string {
	if m != nil {
		return m.CFGPlanURL
	}
	return ""
}

func (m *Plans) GetTFPlanURL() string {
	if m != nil {
		return m.TFPlanURL
	}
	return ""
}

func (m *Plans) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

type History struct {
	Time                 string   `protobuf:"bytes,1,opt,name=Time,proto3" json:"Time,omitempty"`
	State                State    `protobuf:"varint,2,opt,name=State,proto3,enum=State" json:"State,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	Username             string   `protobuf:"bytes,4,opt,name=Username,proto3" json:"Username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *History) Reset()         { *m = History{} }
func (m *History) String() string { return proto.CompactTextString(m) }
func (*History) ProtoMessage()    {}
func (*History) Descriptor() ([]byte, []int) {
	return fileDescriptor_4fb3e7660cb4a0b9, []int{1}
}

func (m *History) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_History.Unmarshal(m, b)
}
func (m *History) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_History.Marshal(b, m, deterministic)
}
func (m *History) XXX_Merge(src proto.Message) {
	xxx_messageInfo_History.Merge(m, src)
}
func (m *History) XXX_Size() int {
	return xxx_messageInfo_History.Size(m)
}
func (m *History) XXX_DiscardUnknown() {
	xxx_messageInfo_History.DiscardUnknown(m)
}

var xxx_messageInfo_History proto.InternalMessageInfo

func (m *History) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *History) GetState() State {
	if m != nil {
		return m.State
	}
	return State_INIT
}

func (m *History) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *History) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type TFMeta struct {
	MetaType             MetaType `protobuf:"varint,1,opt,name=MetaType,proto3,enum=MetaType" json:"MetaType,omitempty"`
	TransactionUUID      string   `protobuf:"bytes,2,opt,name=TransactionUUID,proto3" json:"TransactionUUID,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	Plans                *Plans   `protobuf:"bytes,4,opt,name=Plans,proto3" json:"Plans,omitempty"`
	State                State    `protobuf:"varint,5,opt,name=State,proto3,enum=State" json:"State,omitempty"`
	History              *History `protobuf:"bytes,6,opt,name=History,proto3" json:"History,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TFMeta) Reset()         { *m = TFMeta{} }
func (m *TFMeta) String() string { return proto.CompactTextString(m) }
func (*TFMeta) ProtoMessage()    {}
func (*TFMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_4fb3e7660cb4a0b9, []int{2}
}

func (m *TFMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TFMeta.Unmarshal(m, b)
}
func (m *TFMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TFMeta.Marshal(b, m, deterministic)
}
func (m *TFMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TFMeta.Merge(m, src)
}
func (m *TFMeta) XXX_Size() int {
	return xxx_messageInfo_TFMeta.Size(m)
}
func (m *TFMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_TFMeta.DiscardUnknown(m)
}

var xxx_messageInfo_TFMeta proto.InternalMessageInfo

func (m *TFMeta) GetMetaType() MetaType {
	if m != nil {
		return m.MetaType
	}
	return MetaType_GRAPH
}

func (m *TFMeta) GetTransactionUUID() string {
	if m != nil {
		return m.TransactionUUID
	}
	return ""
}

func (m *TFMeta) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *TFMeta) GetPlans() *Plans {
	if m != nil {
		return m.Plans
	}
	return nil
}

func (m *TFMeta) GetState() State {
	if m != nil {
		return m.State
	}
	return State_INIT
}

func (m *TFMeta) GetHistory() *History {
	if m != nil {
		return m.History
	}
	return nil
}

func init() {
	proto.RegisterEnum("State", State_name, State_value)
	proto.RegisterEnum("MetaType", MetaType_name, MetaType_value)
	proto.RegisterType((*Plans)(nil), "Plans")
	proto.RegisterType((*History)(nil), "History")
	proto.RegisterType((*TFMeta)(nil), "TFMeta")
}

func init() {
	proto.RegisterFile("proto_resource_model/proto_resource_model.proto", fileDescriptor_4fb3e7660cb4a0b9)
}

var fileDescriptor_4fb3e7660cb4a0b9 = []byte{
	// 383 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x4f, 0xab, 0x9b, 0x40,
	0x14, 0xc5, 0x9f, 0x2f, 0xea, 0xd3, 0xfb, 0xda, 0x74, 0x98, 0x95, 0x94, 0x10, 0x82, 0x50, 0x08,
	0x59, 0x18, 0x48, 0xa1, 0x74, 0x6b, 0x6a, 0xfe, 0x15, 0x1b, 0x65, 0xa2, 0x85, 0x74, 0x13, 0x8c,
	0x0e, 0xad, 0x10, 0x9d, 0xa0, 0x93, 0x40, 0x3e, 0x6b, 0xbf, 0x4c, 0x71, 0x34, 0x26, 0x94, 0x2c,
	0xde, 0xca, 0x73, 0x7f, 0x07, 0xcf, 0xcc, 0x3d, 0x0c, 0x8c, 0x8f, 0x05, 0xe3, 0x6c, 0x57, 0xd0,
	0x92, 0x9d, 0x8a, 0x98, 0xee, 0x32, 0x96, 0xd0, 0xc3, 0x43, 0x68, 0x09, 0x68, 0x6e, 0x41, 0xf1,
	0x0f, 0x51, 0x5e, 0xe2, 0x3e, 0xc0, 0xb7, 0xf9, 0xa2, 0xd2, 0x21, 0x71, 0x0d, 0x69, 0x20, 0x0d,
	0x75, 0x72, 0x47, 0x70, 0x0f, 0xf4, 0x60, 0x7e, 0xb5, 0x9f, 0x85, 0x7d, 0x03, 0x18, 0x83, 0x1c,
	0x86, 0x2b, 0xc7, 0xe8, 0x08, 0x43, 0x68, 0xf3, 0x02, 0x2f, 0xcb, 0xb4, 0xe4, 0xac, 0xb8, 0x54,
	0x76, 0x90, 0x66, 0xb4, 0x89, 0x15, 0x1a, 0xf7, 0x40, 0xd9, 0xf0, 0x88, 0x53, 0x11, 0xd6, 0x9d,
	0xa8, 0x96, 0x98, 0x48, 0x0d, 0xf1, 0x00, 0x5e, 0x1d, 0x5a, 0xc6, 0x45, 0x7a, 0xe4, 0x29, 0xcb,
	0x9b, 0xdc, 0x7b, 0x84, 0x3f, 0x82, 0x16, 0x96, 0xb4, 0xc8, 0xa3, 0x8c, 0x1a, 0xb2, 0xb0, 0xdb,
	0xd9, 0xfc, 0x2b, 0x81, 0x1a, 0xcc, 0x7f, 0x50, 0x1e, 0xe1, 0x4f, 0xa0, 0x55, 0xdf, 0xe0, 0x72,
	0xac, 0x8f, 0xef, 0x4e, 0x74, 0xeb, 0x0a, 0x48, 0x6b, 0xe1, 0x21, 0x7c, 0x08, 0x8a, 0x28, 0x2f,
	0xa3, 0xb8, 0x0a, 0x17, 0xbb, 0xd4, 0x4b, 0xfe, 0x8f, 0xdf, 0x70, 0xb3, 0x5e, 0xd3, 0xa9, 0xb8,
	0xd6, 0xeb, 0x44, 0xb5, 0xc4, 0x44, 0x9a, 0xa2, 0xdb, 0xbd, 0x95, 0x47, 0x7b, 0x9b, 0x6d, 0x69,
	0x86, 0x2a, 0xfe, 0xd6, 0xac, 0x66, 0x26, 0x57, 0x63, 0xe4, 0x35, 0x09, 0x58, 0x03, 0x79, 0xb5,
	0x5e, 0x05, 0xe8, 0xa9, 0x52, 0xbe, 0x6b, 0xaf, 0x91, 0x84, 0xdf, 0x83, 0x6e, 0xfb, 0x3e, 0xf1,
	0x7e, 0xda, 0xee, 0x06, 0x3d, 0x63, 0x00, 0xd5, 0x99, 0xf9, 0xae, 0xb7, 0x45, 0x1d, 0xfc, 0x0e,
	0xb4, 0x5a, 0xcf, 0x1c, 0x24, 0x63, 0x1d, 0x94, 0x19, 0x21, 0x1e, 0x41, 0xca, 0xa8, 0x7f, 0xeb,
	0xa8, 0xc2, 0x0b, 0x62, 0xfb, 0x4b, 0xf4, 0x84, 0x5f, 0xa0, 0xf3, 0xdd, 0x9b, 0x22, 0x69, 0xfa,
	0xf5, 0xd7, 0x97, 0xdf, 0x29, 0xff, 0x73, 0xda, 0x5b, 0x31, 0xcb, 0xc6, 0x49, 0x74, 0xa6, 0x09,
	0xe3, 0x09, 0x3d, 0xd7, 0x0f, 0x6b, 0x4c, 0x93, 0x24, 0xa5, 0x0f, 0x1f, 0xd9, 0x5e, 0x15, 0xf4,
	0xf3, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8c, 0xc3, 0x74, 0xb1, 0x98, 0x02, 0x00, 0x00,
}
